### ISSUE TITLE
fabric-ca 1.1.0-alpha is broken

### ISSUE THREAD

**Issue by dimaxgl** [yeasy/docker-hyperledger-fabric#5]
We get a panic when we're trying to init fabric-ca-server:
```
root@18e12151281e:/etc/hyperledger/fabric-ca# fabric-ca-server init -b admin:adminpw
2018/02/21 10:28:15 [INFO] Configuration file location: /etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
panic: Version is not set for fabric-ca library

goroutine 1 [running]:
github.com/hyperledger/fabric-ca/lib/metadata.GetVersion(0x41bbc7, 0xc42027b0e0)
	/go/src/github.com/hyperledger/fabric-ca/lib/metadata/version.go:58 +0x60
github.com/hyperledger/fabric-ca/lib.(*Server).init(0xc42027b0e0, 0xc420277100, 0xc0a792, 0xc420137bf0)
	/go/src/github.com/hyperledger/fabric-ca/lib/server.go:102 +0x29
github.com/hyperledger/fabric-ca/lib.(*Server).Init(0xc42027b0e0, 0xc42027b000, 0x0, 0xc420137c50)
	/go/src/github.com/hyperledger/fabric-ca/lib/server.go:92 +0x38
main.(*ServerCmd).init.func2(0xc42007cd80, 0xc4200d5fa0, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/servercmd.go:102 +0xfc
github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra.(*Command).execute(0xc42007cd80, 0xc4200d5e00, 0x2, 0x2, 0xc42007cd80, 0xc4200d5e00)
	/go/src/github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra/command.go:643 +0x3e8
github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42007cb40, 0xa10e96, 0xc420074c30, 0xc420074c30)
	/go/src/github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra/command.go:734 +0x2fe
github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42007cb40, 0xc4200f43c0, 0xc420074c30)
	/go/src/github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra/command.go:692 +0x2b
main.(*ServerCmd).Execute(0xc420074c30, 0x4, 0x1)
	/go/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/servercmd.go:69 +0x2f
main.RunMain(0xc4200100c0, 0x4, 0x4, 0xc420137f70, 0xa1265b)
	/go/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/main.go:45 +0xb0
main.main()
	/go/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/main.go:27 +0x45
```
It looks like version isn't provided in ldflags?

**Comment by yeasy** [comment]
The image is broken due to a recent change.

Has been resolved. pls re-pull

$ docker pull yeasy/hyperledger-fabric-ca:1.1.0-alpha
$ docker run --rm -it yeasy/hyperledger-fabric-ca:1.1.0-alpha bash
root@904b9b1ba95d:/go/src/github.com/hyperledger/fabric-ca# fabric-ca-server init -b admin:adminpw
2018/02/22 06:50:28 [INFO] Created default configuration file at /etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
2018/02/22 06:50:28 [INFO] Server Version: 1.1.0-alpha
2018/02/22 06:50:28 [INFO] Server Levels: &{Identity:1 Affiliation:1 Certificate:1}
2018/02/22 06:50:28 [INFO] The CA key and certificate files already exist
2018/02/22 06:50:28 [INFO] Key file location: /etc/hyperledger/fabric-ca-server/ca-key.pem
2018/02/22 06:50:28 [INFO] Certificate file location: /etc/hyperledger/fabric-ca-server/ca-cert.pem
2018/02/22 06:50:28 [INFO] Initialized sqlite3 database at /etc/hyperledger/fabric-ca-server/fabric-ca-server.db
2018/02/22 06:50:28 [INFO] Home directory for default CA: /etc/hyperledger/fabric-ca-server
2018/02/22 06:50:28 [INFO] Initialization was successful

**Comment by dimaxgl** [comment]
thx!

**Comment by corpsemxq** [comment]
Still happened when run natively (not on the docker server)

**Comment by sathishsms** [comment]
```
root@osboxes:~/go/bin# ./fabric-ca-server start -b admin:adminpw
2018/04/28 10:00:51 [INFO] Configuration file location: /home/osboxes/go/bin/fabric-ca-server-config.yaml
2018/04/28 10:00:51 [INFO] Starting server in home directory: /home/osboxes/go/bin
panic: Version is not set for fabric-ca library

goroutine 1 [running]:
```

Still happens when running without docker
